#### Numpy
-Numpy is an opean-source libarary in python that provides support for large,multi-dimensional arrays and matrices,along with a collection of mathematical functions to operate on these arrays.
KEY Features:
-Efficient storage-numpy arrays use less memory.
-performance-operations are implemented in c and optimized for performance.
-interoperability-works seamlessly with many other scientific lib like scipy,pandas,and matplotlib.
ARRAY AND MATRIX
ARRAY(NDARRAY)


 DIFFERENEC BETWEEN RANGE AND ARANGE

RANGE:
-Generate a sequence of numbers.
parameters:
range(Start,Stop,Step)
-Start->(default is 0) starting point of the sequence.
-Stop->(required) the end point.
-Step->(default is 1) the difference between each number.


In [1]:
for i in range(9):
    print(i)

0
1
2
3
4
5
6
7
8


ARANGE:

->A function provided by the numpy lib to create a numpy array with evenly spaced values.

->USeful when working with numpy for mathematical operations on arrays.
PARAMETERS:

numpy.arange(Start,Stop,Step)
-Start->(default is 0) Starting poitn of the sequence.
-Stop->(required) the end point.
-Step->(default is 1) the difference between each number,and be a float.


In [1]:
import numpy as np
arr=np.arange(6)
print(arr)

[0 1 2 3 4 5]


In [7]:
#Numpy arrays(ndarray)
#->using np.array(): convert to python list to numpy array.
import numpy as np
list=[1,2,3,4,5,6,7]
newarr=np.array(list)
print(newarr)

[1 2 3 4 5 6 7]


USING np.zero(),np.ones(),np.empty():
#### np.zero(shape):create an array filled with zeros.
#### np.ones(shape):crate an array filled with ones.
#### np.empty(shape):create an array without initializing its values-values will be random.


In [3]:
#np.zeros()
zeros=np.zeros((2,3))
print(zeros)
               

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
#np.noes()
ones=np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
#np.empty()
empty=np.empty((2,2))
print(empty)

[[2.12199579e-314 1.16073170e-311]
 [8.43864123e-321 6.95187041e-310]]


## USING np.arange(),np.linspace()
#### np.arange(start,stop,step)-similar to python range but returns an array.
#### np.linspace(start,stop,num)-generates number evenly spaced values between start and stop.

In [15]:
#np.arange()
range=np.arange(0,10,2)
print(range)


[0 2 4 6 8]


In [19]:
#np.linspace()
linspace=np.linspace(0,2,5)
print(linspace)

[0.  0.5 1.  1.5 2. ]


## PROPERTIES OF NUMPY ARRAYS
 ##### SHAPE:THE DIMENSIONS OF THE ARRAY
 ##### data type: use dtype to specify the data type of the array elements.
 - Number of data types np.int32,np.int64,np.float32,np.float64,np.complex,np.bool_,etc.

In [27]:
arr=np.shape([[1,2,3],[4,6,7]])
print(arr)

(2, 3)


## ARRAY MANIPULATIONS
 ##### Reshaping and Resizing
 ##### Reshape: change the shape of an array without changing its data.


In [45]:
a=np.arange(6)
print(a)
b=a.reshape((2,3))
print(b)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


#### flattening: converting multi-dimensional array into one-dimensional array using flatten() or ravel().
#### Transposing: Swap rows with columns using T


In [49]:
arr=np.array([[[[1,2,3],[4,5,6],[7,8,9]]]])
newarr=arr.flatten()
print(newarr)

[1 2 3 4 5 6 7 8 9]


In [53]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
newarr=arr.T
print(newarr)

[[[1]
  [4]
  [7]]

 [[2]
  [5]
  [8]]

 [[3]
  [6]
  [9]]]


## Concatenation and Stacking
## Concatenate: Combine arrays along a specified axis using np.concatenate().
## Stacking: Use np.vstack() and np.hstack() for vertical and horizontal stacking,respectively.

In [73]:
#concatenate: 
a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])
concatenated=np.concatenate((a,b),axis=0)
print(concatenated)

[[1 2]
 [3 4]
 [5 6]]


In [101]:
#Stacking:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6,]])
vstack=np.vstack((a,b))
print(vstack)

[[1 2]
 [3 4]
 [5 6]]


In [111]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])
b_reshaped = np.repeat(b, 2, axis=0)
h_stack=np.hstack((a,b_reshaped))
print(h_stack)

[[1 2 5 6]
 [3 4 5 6]]


## indexing and slicing
 ## index: Access elements using indices
 ## slicing: Extract subarrays using slicing techniques similar to pyhton lists.

In [4]:
#index
import numpy as np
a=np.array([1,2,3,4,5])
print(a[2])

3


In [7]:
#slicing
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b[0:1,1:3])


[[2 3]]


## ADVANCED INDEXING
 ## Boolean indexing: select elements based on conditions.
 ## fancy indexing: Access elements using an array of indices.

In [9]:
#boolean indexing
a=np.array([1,2,3,4,5])
print(a[a>2])

[3 4 5]


In [31]:
#fancy indexing
a=np.array([1,2,3,4,5,6])
indices=[1,4,5]
print(a[indices])

[2 5 6]


## BOARDCASTING
-Broadcasting:Allows operations on array of different shapes.
Numpy automatically expands the smaller array to match the larger array's shape.

Broadcasting Rules:
1.	If the arrays have a different number of dimensions, prepend the shape of the smaller array with ones until they have the same number of dimensions.
2.	Compare the shapes of the two arrays element-wise, starting from the trailing dimensions. If the sizes of the dimensions are equal or one of them is 1, broadcasting occurs.
3.	If the sizes are incompatible, an error is raised.


In [33]:
a=np.array([[1],[2],[3]])
b=np.array([1,2,3])
c=a+b
print(c)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


## vectorized operations:
To perform element-wise operations on entire array without using explicit loops


In [16]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=a+b   #element-wise add
c=a-b   #element-wise sub
c=a*b   #element-wise multiplication
print(c)

[ 5 12 21 32]


## MATHEMATICAL AND STATISTICAL FUNCTION
 NUMPY provides a comprehensive suite of mathematical functions.
###  basic Arthimetic Operations
 addition,subtraction,multiplication,divide
 

In [18]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
print(np.add(a,b))

[ 7  9 11 13 15]


In [20]:
print(np.subtract(a,b))

[-5 -5 -5 -5 -5]


In [22]:
print(np.multiply(a,b))

[ 6 14 24 36 50]


In [24]:
print(np.divide(a,b))

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


## Statistical Function
Functions like np.mean(),np.median(),np.std(),np.var(),np.sum()

In [30]:
arr=np.array([1,2,3,4,5,6,7])
newarr=np.mean(arr)
print(newarr)


4.0


In [46]:
arr=np.array([1,2,3,4,5,6,7,8])
newarr=np.median(arr)
print(newarr)

4.5


In [48]:
arr=np.array([1,2,3,4,5,6,7])
newarr=np.std(arr)
print(newarr)

2.0


In [50]:
arr=np.array([1,2,3,4,5,6,7,8,9])
newarr=np.sum(arr)
print(newarr)

45


## AGGREGATION FUNCTIONS
Functions like np.min(),np.max(),np.argmax() return the minimum and maximum values,and the index of the maximum value,respectively.

In [54]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
newarr=np.min(arr)
print(newarr)

1


In [58]:
arr=np.array([1,2,3,4,5,6,7,8])
newarr=np.max(arr)
print(newarr)

8


In [60]:
arr=np.array([1,2,3,4,5,6,7,8])
newarr=np.argmax(arr)
print(newarr)

7


In [62]:
arr=np.array([1,2,3,4,5,6,7,8])
newarr=np.argmin(arr)
print(newarr)

0


## UNIVERSAL FUNCTIONS(Ufuncs)
 universal functions(ufuncs):Functions are that operate element-wise on array.they are optimizeed for performance and can handle arrays of different shape and sizes.
 ##### commonly used ufuncs:
 ### mathematical functions: 
 np.sin(),np.tan(),np.cos(),np.exp(),np.log(),np.sqrt(), etc...
 ### Comparison functions:
 np.greater(),np.less(),np.equal(), etc...

In [66]:
a=np.array([0,1,np.pi/2,np.pi])
sin_value=np.sin(a)
print(sin_value)

[0.00000000e+00 8.41470985e-01 1.00000000e+00 1.22464680e-16]


In [70]:
a=np.array([0,1,np.pi/2,np.pi])
cos_value=np.cos(a)
print(cos_value)

[ 1.00000000e+00  5.40302306e-01  6.12323400e-17 -1.00000000e+00]


In [72]:
a=np.array([0,1,np.pi/2,np.pi])
tan_value=np.tan(a)
print(tan_value)

[ 0.00000000e+00  1.55740772e+00  1.63312394e+16 -1.22464680e-16]


In [68]:
a=np.array([0,1,np.pi/2,np.pi])
exp_value=np.exp(a)
print(exp_value)

[ 1.          2.71828183  4.81047738 23.14069263]


In [76]:
a=np.array([0,1,np.pi/2,np.pi])
log_value=np.log(a+1)
print(log_value)

[0.         0.69314718 0.94421571 1.42108041]


##  LINEAR ALGEBRA WITH NUMPY
Numpy provides a comprehensive set of linear algebra functions via the numpy.linalg module.

### Matrix operations
MATRIX MULTIPLICATIONS:Use np.dot() or the @ operator for the matrix multiplication.

In [78]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[8,9]])
c=np.dot(a,b)
print(c)

[[21 24]
 [47 54]]


In [80]:
c=a@b
print(c)

[[21 24]
 [47 54]]


## Determinants and Inverses
#### Determinant:
Calculate the determinant of a matrix using np.linalg.det().
#### inverse:
Find the inverse of matrix using np.linalg.inv().

In [92]:
#Determinant:
a=np.array([[1,0],[0,4]])
det_a=np.linalg.det(a)
print(det_a)

4.0


In [96]:
#inverse
a=np.array([[1,0],[0,1]])
inv_a=np.linalg.inv(a)
print(inv_a)

[[1. 0.]
 [0. 1.]]


## EIGENVALUES AND EIGENVECTORS

#### Eignvalues:
•	Definition: Scalars that provide information about the behavior of linear transformations represented by a matrix.
•o	Interpretation: When a matrix is multiplied by an eigenvector, the result is simply the eigenvector scaled by the eigenvalue.•
o	Example: If A is a matrix and λ is an eigenvalue, the equation is: Av= λv
 Here, v is the eigenvecto#### Eginvectors:
•	Definition: Scalars that provide information about the behavior of linear transformations represented by a matrix.
•o	Interpretation: When a matrix is multiplied by an eigenvector, the result is simply the eigenvector scaled by the eigenvalue.•
o	Example: If A is a matrix and λ is an eigenvalue, the equation is: Av= λv
 Here, v is the eigenvector.
r.


#### Finding Eigenvalues and Eigenvectors:
•	Characteristic Polynomial: To find eigenvalues, solve the characteristic polynomial given by:
det(A−λI)=0
where I is the identity matrix.


In [122]:
import numpy as np
#create matrix
a=np.array([[4,2],[1,3]])
#calculate eignvalues and eignvectors
eignvalues,eignvectors=np.linalg.eig(a)
print(eignvalues,eignvectors)

[5. 2.] [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [118]:
print("Eigenvalues:",eignvalues)

Eigenvalues: [5. 2.]


In [116]:
print("Eigevectors:",eignvectors)

Eigevectors: [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


## Intuition Behind Eigenvalues and Eigenvectors:
#### 
•	Visual Representation:•
o	Imagine applying a transformation represented by a matrix A to a vector. Most vectors will change direction and length. However, eigenvectors are special; they only get stretched or compressed by the eigenvalue factor without changing their direction#### .
•	Applications: Eigenvalues and eigenvectors have significant applications in various fields, includin•:
o	Principal Component Analysis (PCA) in machine learning for dimensionality reducti•n.
o	Stability analysis in systems of differential equatio•	Calculate eigenvalues and eigenvectors using np.linalg.eig().ns.



In [132]:
a=np.array([[4,2],[1,3]])
eignvalues,eignvectors=np.linalg.eig(a)
print(eignvalues,eignvectors)

[5. 2.] [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


## Solving Linear Systems:
-->Using np.linalg.solve() 
to solve a system of linear equations represented as Ax=bAx=bAx=b

In [136]:
a=np.array([[3,1],[1,2]])
b=np.array([9,8])
x=np.linalg.solve(a,b)
print(x)

[2. 3.]


## Random Number Generation
Numpy's random module provieds various functions for generating random numbers,making it essential for simulations and testing

## Generating random Numbers
#### Uniform Distribution:
np.random.rand() generates numbers uniformly distributed between[0,1).
#### Normal Distribution:
np.random.randn() generates numbers from a standard normal distribution(mean=0,std=1)

In [138]:
## uniform distribution
uniform_random=np.random.rand(3,2)
print(uniform_random)

[[0.21144692 0.76849469]
 [0.8301182  0.26628747]
 [0.6761354  0.17387984]]


In [144]:
## normal distribution
normal_randoms=np.random.randn(3,2)
print(normal_randoms)

[[ 0.20152376  2.26440656]
 [ 0.28750404 -0.82896829]
 [-1.82568663 -0.26966877]]


#### Random Integers
Generate random integers with np.random.randint(low,high,size).

In [146]:
random_integer=np.random.randint(1,10,size=(2,3))
print(random_integer)

[[2 8 8]
 [8 8 9]]


#### random Sampling
Randomly shuffle an array using np.random.shuffle().

In [150]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
np.random.shuffle(a)
print(a)

[ 1  5  3  4  8  9  6  2 10  7]


#### random Splitting
array using np.split()-divides an array into multiple sub-arrays.


In [162]:
a=np.array([1,2,3,4,5,6,7,8,9])
b=np.split(a,3)
print(b)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
